name: Publish Docker image
on:
  push:
    tags:
    - v[0-9]*
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Set tag version
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Push 7.4 cli to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./7.4-alpine/Dockerfile
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}:7.4-cli-${{ steps.vars.outputs.tag }}
          target: cli
      -
        name: Push 7.4 web to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./7.4-alpine/Dockerfile
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}:7.4-web-${{ steps.vars.outputs.tag }} 
          target: web
      -
        name: Push 7.4 rootless to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./7.4-alpine/Dockerfile
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}:7.4-web-rootless-${{ steps.vars.outputs.tag }} 
          target: rootless
      -
        name: Push 8.0 cli to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./8.0-alpine/Dockerfile
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}:8.0-cli-${{ steps.vars.outputs.tag }}
          target: cli
      -
        name: Push 8.0 web to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./8.0-alpine/Dockerfile
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}:8.0-web-${{ steps.vars.outputs.tag }} 
          target: web
      -
        name: Push 8.0 rootless to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./8.0-alpine/Dockerfile
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}:8.0-web-rootless-${{ steps.vars.outputs.tag }} 
          target: rootless
      -
        name: Push 8.1 cli to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./8.1-alpine/Dockerfile
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}:8.1-cli-${{ steps.vars.outputs.tag }}
          target: cli
      -
        name: Push 8.1 web to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./8.1-alpine/Dockerfile
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}:8.1-web-${{ steps.vars.outputs.tag }} 
          target: web
      -
        name: Push 8.1 rootless to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./8.1-alpine/Dockerfile
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}:8.1-web-rootless-${{ steps.vars.outputs.tag }} 
          target: rootless
