name: Publish Docker image
on:
  push:
    tags:
    - v[0-9]*
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-24.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Set tag version
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Push 8.1 cli to Docker Hub
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./8.1-alpine/Dockerfile
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}:8.1-cli-${{ steps.vars.outputs.tag }}
          target: cli
      -
        name: Push 8.1 web to Docker Hub
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./8.1-alpine/Dockerfile
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}:8.1-web-${{ steps.vars.outputs.tag }}
          target: web
      -
        name: Push 8.1 rootless to Docker Hub
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./8.1-alpine/Dockerfile
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}:8.1-web-rootless-${{ steps.vars.outputs.tag }}
          target: rootless
      -
        name: Push 8.2 cli to Docker Hub
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./8.2-alpine/Dockerfile
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}:8.2-cli-${{ steps.vars.outputs.tag }}
          target: cli
      -
        name: Push 8.2 web to Docker Hub
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./8.2-alpine/Dockerfile
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}:8.2-web-${{ steps.vars.outputs.tag }}
          target: web
      -
        name: Push 8.2 rootless to Docker Hub
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./8.2-alpine/Dockerfile
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}:8.2-web-rootless-${{ steps.vars.outputs.tag }}
          target: rootless
      -
        name: Push 8.3 cli to Docker Hub
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./8.3-alpine/Dockerfile
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}:8.3-cli-${{ steps.vars.outputs.tag }}
          target: cli
      -
        name: Push 8.3 web to Docker Hub
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./8.3-alpine/Dockerfile
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}:8.3-web-${{ steps.vars.outputs.tag }}
          target: web
      -
        name: Push 8.3 rootless to Docker Hub
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./8.3-alpine/Dockerfile
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}:8.3-web-rootless-${{ steps.vars.outputs.tag }}
          target: rootless
      -
        name: Push 8.4 cli to Docker Hub
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./8.4-alpine/Dockerfile
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}:8.4-cli-${{ steps.vars.outputs.tag }}
          target: cli
      -
        name: Push 8.4 web to Docker Hub
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./8.4-alpine/Dockerfile
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}:8.4-web-${{ steps.vars.outputs.tag }}
          target: web
      -
        name: Push 8.4 rootless to Docker Hub
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./8.4-alpine/Dockerfile
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}:8.4-web-rootless-${{ steps.vars.outputs.tag }}
          target: rootless